src/django_server/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('query.urls', namespace='query'))
]

if settings.DEBUG:  # pragma: no cover
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/query/urls.py
from django.conf.urls import url
from query.views import IndexView, SearchView

app_name = 'main'

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^search/$', SearchView.as_view(), name='search')
]

src/query/views.py
from math import ceil

from django.views.generic import TemplateView
from query.servers import solr, solr1
import re


class IndexView(TemplateView):
    template_name = 'main/index.html'


class SearchView(TemplateView):
    template_name = 'main/search.html'
    paginated_by = 6

    def get(self, request, *args, **kwargs):
        query = request.GET.get('q')
        page = request.GET.get('page')
        try:
            q = re.findall(r"[\w']+", query.replace(":", " "))
        except AttributeError:
            q = []
        try:
            page = int(page)
            page = (1 if page < 1 else page)
        except (ValueError, TypeError):
            page = 1
        context = self.get_context_data(**kwargs)
        context['query'] = query
        context['currentPage'] = page

        result = solr1.get_result(q, 0, 0)
        result1 = solr.get_result(q, 0, 0)
        solr_result = int(result['response']['numFound'])
        result['response']['numFound'] += result1['response']['numFound']
        context['numPage'] = ceil(result['response']['numFound'] / self.paginated_by)
        context['responseHeader'] = result['responseHeader']

        start_point = (page - 1) * self.paginated_by
        end_point = (page - 1) * self.paginated_by + self.paginated_by
        # solr1_result = int(result1['response']['numFound'])

        if end_point <= solr_result:
            res = solr1.get_result(q, start_point, self.paginated_by)
            result['response']['docs'] = res['response']['docs']

        elif start_point < solr_result <= end_point:
            res = solr1.get_result(q, start_point, self.paginated_by)
            doc_num_res = len(res['response']['docs'])
            res1 = solr.get_result(q, 0, self.paginated_by - doc_num_res)
            result['response']['docs'] = res['response']['docs'] + res1['response']['docs']

        elif solr_result < start_point:
            res = solr.get_result(q, start_point - solr_result, self.paginated_by)
            result['response']['docs'] = res['response']['docs']

        context['results'] = result['response']
        return self.render_to_response(context)

src/templates/main/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zxx" class="no-js">
<head>
    <!-- Mobile Specific Meta -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Favicon-->
    <link rel="shortcut icon" href="{% static 'img/fav.png' %}">
    <!-- Author Meta -->
    <meta name="author" content="codepixer">
    <!-- Meta Description -->
    <meta name="description" content="">
    <!-- Meta Keyword -->
    <meta name="keywords" content="">
    <!-- meta character set -->
    <meta charset="UTF-8">
    <title>Agrosearch</title>
    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,500,600" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500i" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/themify-icons/0.1.2/css/themify-icons.css">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>
<body>
<section class="home-banner-area relative">
    <div class="container">
        <div class="row fullscreen d-flex align-items-center justify-content-center">
            <div class="banner-content col-lg-8 col-md-12">
                <h1 class="wow fadeIn" data-wow-duration="4s" style="color: black">AGROSEARCH</h1>
                <p class="text-black">
                    Farming practices made easy!<br>
                </p>
                <div class="input-wrap">
                    <form action="{% url 'query:search' %}" class="form-box d-flex justify-content-between" method="get">
                        <input type="text" placeholder="Search..." class="form-control" name="q">
                        <button type="submit" class="btn search-btn">Search</button>
                    </form>
                </div>
                <h4 class="text-black">Quick Links</h4>
                <div class="courses pt-20">
                    <a href="{% url 'query:search' %}?q=agricultural+practices" data-wow-duration="1s" data-wow-delay=".3s"
                       class="primary-btn transparent mr-10 mb-10 wow fadeInDown"
                       style="color: black;border-color: black">Agricultural Practices</a>
                    <a href="{% url 'query:search' %}?q=crops" data-wow-duration="1s" data-wow-delay=".6s"
                       class="primary-btn transparent mr-10 mb-10 wow fadeInDown"
                       style="color: black;border-color: black">Type of Crops</a>
                    <a href="{% url 'query:search' %}?q=disease+crop" data-wow-duration="1s" data-wow-delay=".9s"
                       class="primary-btn transparent mr-10 mb-10 wow fadeInDown"
                       style="color: black;border-color: black">Crop Diseases</a>
                    <a href="{% url 'query:search' %}?q=fertilizers" data-wow-duration="1s" data-wow-delay="1.2s"
                       class="primary-btn transparent mr-10 mb-10 wow fadeInDown"
                       style="color: black;border-color: black">
                        Fertilizers & Pesticides
                    </a>
                    <a href="{% url 'query:search' %}?q=help" data-wow-duration="1s" data-wow-delay="1.5s"
                       class="primary-btn transparent mr-10 mb-10 wow fadeInDown"
                       style="color: black;border-color: black">Helpline</a>
                </div>
            </div>
        </div>
    </div>
</section>
<script src="{% static 'js/vendor/jquery-2.2.4.min.js' %}"></script>
<script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>
<script src="{% static 'js/wow.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
</body>
</html>

src/templates/main/search.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zxx" class="no-js">
<head>
    <title>{{ query }} | AgroSearch Results </title>
    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,500,600" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500i" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/themify-icons/0.1.2/css/themify-icons.css">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>
<body style="background-image: linear-gradient(#C0CA83,white);background-repeat: no-repeat;background-attachment: fixed;">
<!-- Header Section -->
<div class="header">
    <a href="{% url 'query:index' %}" class="logo">Agrosearch</a>
    <div class="header-right">
        <div class="search-container">
            <form action="{% url 'query:search' %}" method="get">
                <input type="text" placeholder="Search.." name="q" value="{{ query }}">
                <button data-wow-duration="1s" data-wow-delay="1.5s"
                        class="primary-btn transparent mr-10 mb-10 wow fadeInDown"
                        style="color: black;border-color: green">Search
                </button>
            </form>
        </div>
    </div>
</div>
{#<div class="container">#}
{#    {% for doc in results.docs %}#}
{#        <div class="row">#}
{#            <div class="col-12">#}
{#                <a href="{{ doc.url }}">#}
{#                    <div class="" href="{{ doc.url }}">#}
{#                        <h3>{{ doc.title }}</h3>#}
{#                        <h6>{{ doc.url }}</h6>#}
{#                    </div>#}
{#                </a>#}
{#            </div>#}
{#        </div>#}
{#    {% endfor %}#}
{#</div>#}
<!-- Main Section -->
<div class="container">
    {% if results.numFound %}
        <h5>{{ results.numFound }} results found in {{ responseHeader.QTime }} ms</h5>
        {% for doc in results.docs %}
            <div class="pt-5 pl-5 pr-5">
                <a href="{{ doc.url }}">
                    <div class="title-div">
                        <h4>{{ doc.title }}</h4>
                        <h6>{{ doc.url | truncatechars:'60'}}</h6>
                    </div>
                </a>
                <div class="content-div">
                    {{ doc.content | truncatewords:'50' }}
                </div>
            </div>
        {% endfor %}
        <div class="container pt-3 pb-5" align="center">
            <div class="pagination">
                {% if currentPage > 1 %}
                    <a href="{% url 'query:search' %}?q={{ query }}&page={{ currentPage|add:"-1" }}">&laquo; Prev</a>
                {% endif %}
                {% if currentPage < numPage %}
                    <a href="{% url 'query:search' %}?q={{ query }}&page={{ currentPage|add:"1" }}"> Next &raquo;</a>
                {% endif %}
            </div>
        </div>
    {% else %}
        <div class="container">
            <h3 align="center">No results found, please try another keyword</h3>
        </div>
    {% endif %}
</div>
</body>
</html>